apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: heart-disease-api
  namespace: mlops
  labels:
    app: heart-disease-api
spec:
  selector:
    matchLabels:
      app: heart-disease-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s

